### ISSUE TITLE
Multiple ESP modules

### ISSUE THREAD

**Issue by oxigen-dev** [fsaris/EspHome-AwoX-BLE-mesh-hub#17]
Hi @fsaris ,

I'd like to ask your opinion about using multiple ESP modules as I can't cover all of my lamps with one module due to Bluetooth range limitations.Will it work or if two ESPs are in range then there can be some conflict?

Thanks!

**Comment by fsaris** [comment]
if they are both in reach of the same light it could be that they try to connect to the "wrong" light.

in general the ESP modules will not conflict with each other.

I'm currently looking into an option to configure the devices the component should "handle". Have the possibility to setup a "static" list of devices instead of only relying on the scan results. Also to handle the issues like https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/issues/8

**Comment by oxigen-dev** [comment]
> if they are both in reach of the same light it could be that they try to connect to the "wrong" light.
> 
> in general the ESP modules will not conflict with each other.
> 
> I'm currently looking into an option to configure the devices the component should "handle". Have the possibility to setup a "static" list of devices instead of only relying on the scan results. Also to handle the issues like #8

Perfect, thanks!
